package com.homeprojects.jvmstudy.parser.statements;

public enum StatementType {

    BLOCK_STATEMENT,
    EXPRESSION_STATEMENT,
    VARIABLE_DECLARATION_STATEMENT,
    TYPE_DECLARATION_STATEMENT,
    VARIABLE_REASSIGNMENT_STATEMENT,
    IF_STATEMENT,
    ELSE_STATEMENT,
    WHILE_STATEMENT,
    FOR_STATEMENT
}